version: '3.9'

services:
  nginx:
      image: nginx
      ports:
          - '4173:80'
      volumes:
          - ./dist/:/usr/share/nginx/html
          - ./nginx:/etc/nginx/conf.d/
  dev:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - '5173:5173'
    entrypoint: ["npm","run","build"]
